version: "3.4"

services:

  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
      
  mongoDb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "${MONGO_VOLUMES}:/data/db"
    networks:
      - mydockernetwork      
      
  postgressDb:
    image: postgres
    container_name: postgressDb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "${POSTGRES_VOLUMES}:/var/lib/mysql"
    networks:
      - mydockernetwork
      

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local   
      
networks:
  mydockernetwork:
    driver: bridge         