version: "3.8"

services:

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper              
      
  postgressDb:
    image: postgres
    container_name: postgressDb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "${POSTGRES_VOLUMES}:/var/lib/mysql"
    networks:
      - mydockernetwork
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_SENHA}
    ports:
      - "16543:80"
    volumes:
      - "${PGADMIN_VOLUMES}:/root/.pgadmin"
    networks:
      - mydockernetwork
    depends_on:
      - postgressDb         
      
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"    

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017  
     

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local   
      
networks:
  mydockernetwork:
    driver: bridge    