global using Microsoft.Extensions.DependencyInjection;
global using SocialMidia.Write.Application.Commands;
global using SocialMidia.Write.Application.Dispatchers;
global using SocialMidia.Write.Application.Extensions;
global using SocialMidia.Write.Application.Handlers;
global using SocialMidia.Write.Application.Interfaces;
global using SocialMidia.Write.Domain.Aggregates;
global using SocialMidia.Write.Domain.Interfaces;
global using _Shared.Domain.Messages;